- name: Restart httpd
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted

- name: Restart dhcpd
  ansible.builtin.systemd_service:
    name: dhcpd
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
