- name: Configure mirror
  hosts: mirror

  tasks:

    - name: DEBUG - inventory_hostname
      ansible.builtin.debug:
        var: inventory_hostname
    - name: DEBUG - ansible_host
      ansible.builtin.debug:
        var: ansible_host
