##### Install ##################################################################

- name: Install dhcpd package
  ansible.builtin.package:
    name: dhcp-server
    state: present

- name: Enable dhcpd service
  ansible.builtin.systemd_service:
    name: dhcpd
    enabled: true
    masked: false

- name: Allow dhcpd in firewall
  ansible.posix.firewalld:
    service: dhcp
    state: enabled
    permanent: true
    immediate: true
    offline: true

##### Config ###################################################################

- name: Create dhcpd config
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: '0644'
  notify: Restart dhcpd
