- name: Include httpd
  ansible.builtin.include_tasks:
    file: httpd.yml

# DEBUG FIXME
# - name: Include dhcpd
#   ansible.builtin.include_tasks:
#     file: dhcpd.yml

- name: Include tftpd
  ansible.builtin.include_tasks:
    file: tftpd.yml
