network --bootproto=dhcp
url      --url="http://192.168.123.2/iso/rhel-9.5-x86_64-dvd/BaseOS/"
repo --baseurl="http://192.168.123.2/iso/rhel-9.5-x86_64-dvd/AppStream/" --name="AppStream"

# IMPORTANT:  Lab use only!!!  You should _definitely_ change this password.
user --name=ansible --password=ansible --groups=wheel --gecos="Ansible service account"
rootpw --lock

text
reboot
firstboot --disable
keyboard --xlayouts='us'
lang en_US.UTF-8
timezone America/New_York --utc
selinux --enforcing
firewall --enabled --ssh

zerombr
clearpart --all --initlabel
autopart

%addon com_redhat_kdump --disable
%end

%packages
@^minimal-environment
kexec-tools
%end

%post
curl -sfL http://192.168.123.2/ks/rhel9.sh | bash
%end
